import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@fortawesome/fontawesome-free/css/all.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "./globals.css";
import { Navbar } from "./_components/Navbar/Navbar";
import { Toaster } from "@/components/ui/sonner";
import Footer from "./_components/Footer/Footer";
import UserProvider from "image/UserProvider";
import CounterProvider from "image/CountProvider";

const InterFont = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${InterFont.className} flex flex-col min-h-screen`}>
        <UserProvider>
          <CounterProvider>
  
            <Navbar />

    
            <main className="flex-1 p-5">{children}</main>

            <Toaster />

            <Footer />
          </CounterProvider>
        </UserProvider>
      </body>
    </html>
  );
}
